[package]
name = "piecut"
version = "1.0.0"
authors = ["Daniel May <daniel.may@mailbox.org>"]
description = "Find files sorted by size and clean them up."
license = "MIT"
edition = "2018"

[dependencies]
walkdir = "2"
clap = "2.33"
piechart = "0.1"

[profile.release]
lto = true
codegen-units = 1